# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: true

warnings_are_errors: true

matrix:
  include:
    - name: "Spark 2.4.3 (R release, oraclejdk8) with Databricks Connect"
      r: release
      r_packages:
        - glmnet
      env:
        - SPARK_VERSION="2.4.3"
        - JAVA_VERSION=oraclejdk8
        - CODE_COVERAGE="true"
        - DATABRICKS_CONNECT="true"
  allow_failures:
    - env: R_DEVEL_PACKAGES="true"

before_install:
  - if [[ ! -z "$JAVA_VERSION" ]]; then jdk_switcher use $JAVA_VERSION ; fi
  - echo $JAVA_HOME
  - if [[ ! -z "$ARROW_VERSION" ]]; then chmod +x ./ci/arrow-$ARROW_SOURCE.sh ; "./ci/arrow-$ARROW_SOURCE.sh" $ARROW_VERSION; fi
  - if [[ $SPARK_VERSION == "master" ]]; then chmod +x ./ci/spark-master-install.sh ; "./ci/spark-master-install.sh"; fi
  - if [[ $ARROW_ENABLED == "true" ]]; then Rscript ci/.travis.R --arrow $ARROW_BRANCH; fi
  - |
    if [[ $DATABRICKS_CONNECT == "true" ]]; then
      pip install databricks-connect==5.5.3
      DATABRICKS_ADDRESS=https://westus2.azuredatabricks.net
      DATABRICKS_API_TOKEN=dapi6c22303f731eb3b52f98f4a0f932d575
      DATABRICKS_CLUSTER_ID=1203-221219-team279
      DATABRICKS_ORG_ID=5112643644973830
      DATABRICKS_PORT=15001
      databricks-connect get-jar-dir
      databricks-connect get-spark-home
      databricks-connect test
      export SPARK_HOME=$(databricks-connect get-spark-home)
    fi

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz

    if [[ $CODE_COVERAGE == "true" ]]; then
      Rscript ci/.travis.R --coverage
    else
      Rscript ci/.travis.R --testthat
    fi

after_failure:
  - |
    grep -B 10 -A 20 ERROR /tmp/sparklyr.log
